version: '3'

services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sdvrwgz46ezg0uatc2h6dvy8n
      MYSQL_DATABASE: "demo"
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  vault:
    image: vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
      VAULT_DEV_ROOT_TOKEN_ID: 'the-dev-key'
      VAULT_TOKEN: 'test'
    cap_add:
      - IPC_LOCK
    healthcheck:
      retries: 5
    command: server -dev
